version: '3'

services:
  spring-boot:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8082:8082"
    environment:
      SPRING_DATA_MONGODB_URI: "mongodb+srv://admin:CYYmDcJoYv7w93ej@cluster0.jwom6.mongodb.net/restaurant?retryWrites=true&w=majority"
  angular:
    build: ./client
    ports:
      - "0.0.0.0:4200:4200"
    
    
    
 
      
      
      
